version: '3.8'

services:
  web:
    build: .
    image: mcd-reciept
    container_name: mcd-reciept-web
    restart: unless-stopped
    ports:
      - "5005:5000"
    volumes:
      - /home/milos/McdQrcodes:/app/db
    command: gunicorn --workers 1 --threads 1 --timeout 60 -b 0.0.0.0:5000 app:app

  worker:
    build: .
    image: mcd-reciept
    container_name: mcd-reciept-worker
    restart: unless-stopped
    volumes:
      - /home/milos/McdQrcodes:/app/db
    command: python worker.py